msm: vidc: Fix compilation
../drivers/media/platform/msm/vidc/msm_vidc_res_parse.c: In function 'msm_vidc_load_freq_table':
../drivers/media/platform/msm/vidc/msm_vidc_res_parse.c:572:33: error: 'cmp_load_freq_table' undeclared (first use in this function); did you mean 'load_freq_table'?
  572 |    sizeof(*res->load_freq_tbl), cmp_load_freq_table, NULL);
      |                                 ^~~~~~~~~~~~~~~~~~~
      |                                 load_freq_table

* cmp_load_freq_table was renamed to just cmp

Signed-off-by: FedorShatokhin2005 <groza01i@gmail.com>